# Generated by Django 3.2.5 on 2021-07-17 18:48

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20210717_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
